// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zQ8H2d6KK0vjf3Baf6fZ3aPYO3xKx90',
    appId: '1:718005686286:web:87e2953becdd3c54afec5f',
    messagingSenderId: '718005686286',
    projectId: 'expense-tracker-17255',
    authDomain: 'expense-tracker-17255.firebaseapp.com',
    storageBucket: 'expense-tracker-17255.firebasestorage.app',
    measurementId: 'G-WHBB66VKXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATq2DmdcrzqxZ1ViU8AkYA4b-yU4cOEpM',
    appId: '1:718005686286:android:7fd80d6918f15434afec5f',
    messagingSenderId: '718005686286',
    projectId: 'expense-tracker-17255',
    storageBucket: 'expense-tracker-17255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiM3iC04Jr9iOdD_KRbzLF2vFHK9ZPmsc',
    appId: '1:718005686286:ios:7993e1f9226fae5bafec5f',
    messagingSenderId: '718005686286',
    projectId: 'expense-tracker-17255',
    storageBucket: 'expense-tracker-17255.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiM3iC04Jr9iOdD_KRbzLF2vFHK9ZPmsc',
    appId: '1:718005686286:ios:7993e1f9226fae5bafec5f',
    messagingSenderId: '718005686286',
    projectId: 'expense-tracker-17255',
    storageBucket: 'expense-tracker-17255.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zQ8H2d6KK0vjf3Baf6fZ3aPYO3xKx90',
    appId: '1:718005686286:web:da152366a1410ad0afec5f',
    messagingSenderId: '718005686286',
    projectId: 'expense-tracker-17255',
    authDomain: 'expense-tracker-17255.firebaseapp.com',
    storageBucket: 'expense-tracker-17255.firebasestorage.app',
    measurementId: 'G-6850V3GEGM',
  );
}
